version: 2

jobs:
  build:
    machine: true
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps: 
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: mkdir $CIRCLE_TEST_REPORTS/core
      - run: mkdir $CIRCLE_TEST_REPORTS/entity
      - run: mkdir $CIRCLE_TEST_REPORTS/transient
      - run: mkdir $CIRCLE_TEST_REPORTS/service
      - run: mkdir $CIRCLE_TEST_REPORTS/process
      - run: mkdir $CIRCLE_TEST_REPORTS/dao    
      - run: npm install -g junit-merge verify-junit-xml
      - run: docker-compose --verbose -f meta/docker/slatwall-ci/docker-compose-circleci.yml up -d
      - run: sudo mkdir -p meta/tests/testresults/xml/integration
      - run: sudo chmod -R 777 meta/tests/testresults
      #- run:
      #    command: if [[ ! -z $SAUCE_USERNAME ]] ; then cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --pidfile sc.pid --readyfile ~/sauce_is_ready --tunnel-identifier $CIRCLE_BUILD_NUM; fi
      #    background: true
      - run: sleep 10
      - run: curl http://localhost:80
      - run: sleep 5
      # This is based on your 1.0 configuration file or project settings
      #- run:
      #    command: cd meta/docker/slatwall-ci && docker-compose exec slatwallweb ant -f /var/www/meta/tests/build.xml run-junit -Dslatwall.outputfile "results" -Dtest.directory "meta.tests.unit";
      #    no_output_timeout: 1800s
      - run: curl http://localhost:80/meta/tests/test-runner/index.cfm\?opt_run\=true\&method\=notRemote\&testSpecs\=\&target\=meta%2Ftests%2Funit%2Fcore\&opt_recurse\=true\&labels\=\&reporter\=JUnit > /tmp/circleci-test-results/core/results.xml
      - run: curl http://localhost:80/meta/tests/test-runner/index.cfm\?opt_run\=true\&method\=notRemote\&testSpecs\=\&target\=meta%2Ftests%2Funit%2Fentity\&opt_recurse\=true\&labels\=\&reporter\=JUnit > /tmp/circleci-test-results/entity/results.xml
      - run: curl http://localhost:80/meta/tests/test-runner/index.cfm\?opt_run\=true\&method\=notRemote\&testSpecs\=\&target\=meta%2Ftests%2Funit%2Fprocess\&opt_recurse\=true\&labels\=\&reporter\=JUnit > /tmp/circleci-test-results/process/results.xml
      - run: curl http://localhost:80/meta/tests/test-runner/index.cfm\?opt_run\=true\&method\=notRemote\&testSpecs\=\&target\=meta%2Ftests%2Funit%2Fservice\&opt_recurse\=true\&labels\=\&reporter\=JUnit > /tmp/circleci-test-results/service/results.xml
      - run: curl http://localhost:80/meta/tests/test-runner/index.cfm\?opt_run\=true\&method\=notRemote\&testSpecs\=\&target\=meta%2Ftests%2Funit%2Ftransient\&opt_recurse\=true\&labels\=\&reporter\=JUnit > /tmp/circleci-test-results/transient/results.xml
      - run: curl http://localhost:80/meta/tests/test-runner/index.cfm\?opt_run\=true\&method\=notRemote\&testSpecs\=\&target\=meta%2Ftests%2Funit%2Fdao\&opt_recurse\=true\&labels\=\&reporter\=JUnit > /tmp/circleci-test-results/dao/results.xml
      #- run: junit-merge -o /tmp/circleci-test-results/results.xml /tmp/circleci-test-results/core/results.xml /tmp/circleci-test-results/entity/results.xml /tmp/circleci-test-results/process/results.xml /tmp/circleci-test-results/transient/results.xml /tmp/circleci-test-results/dao/results.xml /tmp/circleci-test-results/service/results.xml
      #- run: verify-junit-xml /tmp/circleci-test-results/results.xml
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
  deploy:
    machine: true
    steps:
      - checkout
      - run: git config --global user.email "info@slatwallcommerce.com"
      - run: git config --global user.name "ten24 (Slatwall Robot)"
      - run: git config --global push.default current
      - run: npm install -g webpack@3.3.0 gulp less webpack-cli
      - run: npm install --only=dev
      - run: npm link
      - run: pip install awscli
      - run: npm run buildHibachi:prod
      #- run: cd admin/client && gulp gen-ts-refs
      - run: npm run buildSlatwall:prod
      - run: cd admin/client/css && lessc main.less main.css
      - run: meta/ci/version_merge.sh
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
              branches:
                only: 
                  - master
                  - hotfix
                  - develop 
                  - /develop-.*/
              
