version: 2

jobs:
  build:
    machine: true
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps: 
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: docker-compose --verbose -f meta/docker/slatwall-ci/docker-compose-circleci.yml up -d
      - run: sudo mkdir -p meta/tests/testresults/xml/integration
      - run: sudo chmod -R 777 meta/tests/testresults
      #- run:
      #    command: if [[ ! -z $SAUCE_USERNAME ]] ; then cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --pidfile sc.pid --readyfile ~/sauce_is_ready --tunnel-identifier $CIRCLE_BUILD_NUM; fi
      #    background: true
      - run: sleep 10
      - run: curl http://localhost:80
      # This is based on your 1.0 configuration file or project settings
      - run:
          command: cd meta/docker/slatwall-ci && docker-compose exec slatwallweb ant -f /var/www/meta/tests/build.xml run-junit -Dslatwall.outputfile "results" -Dtest.directory "meta.tests.unit";
          no_output_timeout: 1800s
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
  deploy:
    machine: true
    steps:
      - checkout
      - run: git config --global user.email "info@slatwallcommerce.com"
      - run: git config --global user.name "Big Boy (Slatwall Robot)"
      - run: git config --global push.default current
      - run: npm install -g webpack@1.13.3 gulp less
      - run: npm install gulp gulp-inject@3 gulp-chmod@1.3.0 gulp-util run-sequence webpack@1.13.3 force-case-sensitivity-webpack-plugin strip-loader ng-annotate-webpack-plugin tsify typescript ts-loader@1.3.0 md5 blueimp-md5
      - run: pip install awscli
      - run: cd org/Hibachi/client && gulp gen-ts-refs && webpack --config webpack-frontend-production.config.js -p --display-error-details
      - run: cd admin/client && gulp gen-ts-refs
      - run: cd admin/client && webpack --config webpack-production.config.js -p --display-error-details
      - run: cd admin/client/css && lessc main.less main.css
      - run: meta/ci/version_merge.sh
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
              branches:
                only: 
                  - master
                  - hotfix
                  - develop 
                  - /develop-.*/
              
