slatwallweb:
  build: .
  ports:
   - "80:8888"
  volumes:
   - ../../../:/var/www
  links:
   - slatwalldb
  environment:
   MYSQL_ROOT_PASSWORD : CiPassword
   MYSQL_HOST : slatwalldb
   MYSQL_DATABASE : Slatwall
   LUCEE_PASSWORD: CiPassword
   LUCEE_JAVA_OPTS: -Xms1024m -Xmx1024m
slatwalldb:
  image: mysql
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD : CiPassword
   MYSQL_DATABASE : Slatwall
