version: '3'
services:
  slatwallweb:
    build: .
    volumes:
      - ../../../:/var/www/
    ports:
     - "80:8888"
    links:
     - slatwalldb
    environment:
     MYSQL_ROOT_PASSWORD : NOT_SECURE_CHANGE
     MYSQL_HOST : slatwalldb
     MYSQL_PORT : 3306
     MYSQL_DATABASE : Slatwall
     LUCEE_PASSWORD: NOT_SECURE_CHANGE
     LUCEE_JAVA_OPTS: -Xms1024m -Xmx1024m
  slatwalldb:
    image: mysql:5.7
    ports:
     - "3300:3306"
    environment:
     MYSQL_ROOT_PASSWORD : NOT_SECURE_CHANGE
     MYSQL_DATABASE : Slatwall
