import cartOrderItem from './cartOrderItem'

export default interface cart {
    orderTypeCode: string,
    orderID: string ,
    VATTotal: number,
    FSNumber: string,
    importFlexshipNumber:string,
    fulfillmentDiscountAmountTotal: number,
    fulfillmentChargeAfterDiscountTotal: number,
    miscChargeAmount: string,
    promotionCodes: Array<any>,
    orderSource: string,
    redeemPoints: string,
    orderFulfillmentWithShippingMethodOptionsIndex: number,
    errors: object,
    calculatedPersonalVolumeSubtotal: number,
    orderRequirementsList: string,
    orderPartnerNumber: string,
    billingAddress: object,
    undeliverableOrderReasons: string,
    commissionPeriodCode: string ,
    orderAndItemDiscountAmountTotal: number,
    orderStatusCode: string,
    orderItems: Array<cartOrderItem>,
    orderCountryCode: string,
    subtotal: number,
    businessDate: string,
    requiresFulfillment: boolean,
    processObjects: object,
    remoteAmountTotal: string,
    commissionPeriod: string,
    fulfillmentTotal: number,
    orderAccountNumber: string,
    orderFulfillments: Array<object>,
    hasErrors: false,
    orderPayments: Array<object>,
    total: number,
    currencyCode: string,
    importOriginalRMANumber: string,
    appliedPromotionMessages: Array<any>,
    monatOrderType: object,
    priceLevelCode: string,
    promotionCodeList: string,
    messages:object,
    totalItemQuantity: number,
    taxTotal: number,
    discountTotal: number,
    orderSourceCode: string,
    invoiceNumber: string,
    orderNotes: string,
    eligiblePaymentMethodDetails: Array<object>,
    calculatedTotal: number,
    initialOrderFlag: string,
    orderOpenDateTime: string
}

