import { OrderTemplateItem } from './OrderTemplateItem';

export interface OrderTemplate {
    billingAccountAddress_address_verificationJson: string;
    shippingAccountAddress_address_postalCode: string;
    vatTotal: number;
    scheduleOrderNextPlaceDateTime: string;
    shippingMethod_shippingMethodID: string;
    billingAccountAddress_accountAddressName: string;
    billingAccountAddress_address_locality: string;
    accountPaymentMethod_creditCardLastFour: string;
    site_siteName: string;
    account_lastName: string;
    shippingAccountAddress_address_streetAddress: string;
    orderTemplateID: string;
    accountPaymentMethod_expirationYear: string;
    billingAccountAddress_address_city: string;
    frequencyTerm_termID: string;
    createdDateTime: string;
    shippingAccountAddress_address_stateCode: string;
    account_accountNumber: string;
    scheduleOrderDayOfTheMonth: number;
    shippingAccountAddress_address_verificationJson: string;
    orderTemplateStatusType_typeName: string;
    shippingMethod_shippingMethodName: string;
    orderTemplateStatusType_systemCode: string;
    shippingAccountAddress_accountAddressID: string;
    calculatedSubTotal: number;
    purchasePlusTotal: number;
    calculatedFulfillmentTotal: number;
    billingAccountAddress_address_street2Address: string;
    frequencyTerm_termName: string;
    calculatedOrderTemplateItemsCount: number;
    shippingAccountAddress_address_locality: string;
    account_firstName: string;
    accountPaymentMethod_accountPaymentMethodID: string;
    statusCode: string;
    billingAccountAddress_accountAddressID: string;
    shippingAccountAddress_address_countryCode: string;
    fulfillmentHandlingFeeTotal: number;
    currencyCode: string;
    billingAccountAddress_address_stateCode: string;
    account_accountID: string;
    orderTemplateName: string;
    billingAccountAddress_address_countryCode: string;
    qualifiesForOFYProducts: boolean;
    shippingAccountAddress_address_street2Address: string;
    shippingAccountAddress_address_city: string;
    orderTemplateItems ?: OrderTemplateItem[];
    billingAccountAddress_address_postalCode: string;
    taxTotal: number;
    shippingAccountAddress_accountAddressName: string;
    billingAccountAddress_address_streetAddress: string;
    calculatedTotal: number;
    accountPaymentMethod_expirationMonth: string;
    account_primaryEmailAddress_emailAddress: string;
}