import { OrderTemplateItem } from './OrderTemplateItem';

export interface OrderTemplate {
    account_accountID                              : string;
    account_accountNumber                          : string;
    account_firstName                              : string;
    account_lastName                               : string;
    account_primaryEmailAddress_emailAddress       : string;
    accountPaymentMethod_accountPaymentMethodID    : string;
    accountPaymentMethod_creditCardLastFour        : string;
    accountPaymentMethod_expirationMonth           : string;
    accountPaymentMethod_expirationYear            : string;
    billingAccountAddress_accountAddressID         : string;
    billingAccountAddress_accountAddressName       : string;
    billingAccountAddress_address_city             : string;
    billingAccountAddress_address_countryCode      : string;
    billingAccountAddress_address_locality         : string;
    billingAccountAddress_address_postalCode       : string;
    billingAccountAddress_address_stateCode        : string;
    billingAccountAddress_address_street2Address   : string;
    billingAccountAddress_address_streetAddress    : string;
    billingAccountAddress_address_verificationJson : string;
    calculatedFulfillmentTotal                     : number;
    calculatedOrderTemplateItemsCount              : number;
    calculatedSubTotal                             : number;
    calculatedTotal                                : number;
    createdDateTime                                : string;
    currencyCode                                   : string;
    frequencyTerm_termID                           : string;
    frequencyTerm_termName                         : string;
    fulfillmentHandlingFeeTotal                    : number;
    orderTemplateID                                : string;
    orderTemplateItems                             ?: OrderTemplateItem[];
    orderTemplateName                              : string;
    orderTemplateStatusType_systemCode             : string;
    orderTemplateStatusType_typeName               : string;
    purchasePlusTotal                              : number;
    qualifiesForOFYProducts                        : boolean;
    scheduleOrderDayOfTheMonth                     : number;
    scheduleOrderNextPlaceDateTime                 : string;
    shippingAccountAddress_accountAddressID        : string;
    shippingAccountAddress_accountAddressName      : string;
    shippingAccountAddress_address_city            : string;
    shippingAccountAddress_address_countryCode     : string;
    shippingAccountAddress_address_locality        : string;
    shippingAccountAddress_address_postalCode      : string;
    shippingAccountAddress_address_stateCode       : string;
    shippingAccountAddress_address_street2Address  : string;
    shippingAccountAddress_address_streetAddress   : string;
    shippingAccountAddress_address_verificationJson: string;
    shippingMethod_shippingMethodID                : string;
    shippingMethod_shippingMethodName              : string;
    site_siteName                                  : string;
    statusCode                                     : string;
    taxTotal                                       : number;
    vatTotal                                       : number;
}