export default {
  stackedContent: {
    'footer/copywriteDate': 2021,
    'header/main-navigation': '<ul><li><a href="/">Home</a>&nbsp;</li><li><a href="/about">About</a></li><li><a href="/contact">Contact</a></li></ul>',
    'footer/stay-informed': '<h3>Stay Informed</h3><p>Sign up to receive any updates on pricing, specials, industry events and lcoal training at our facility!</p>',
    'footer/contact-us': '<h4>Can&#39;t find what you are looking for?</h4><p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero&#39;s De Finibus Bonorum et Malorum for use in a type specimen book.</p><p><a class="btn" href="/contact/">Contact Us</a></p>',
    'header/productCategories': [
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6f7a36001d',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'keyblanksautomotive',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column1',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808a74bb14de0174bc712e870021',
        cmsContentIDPath: ' ',
        customBody: '<a class="product-dropdown-header" href="/">Accessories</a>\r\n\r\n<ul>\r\n\t<li><a href="/">Key Cabinets</a></li>\r\n\t<li><a href="/">Key Storage</a></li>\r\n\t<li><a href="/">Key Tags</a></li>\r\n\t<li><a href="/">Key Caps</a></li>\r\n\t<li><a href="/">Wrist Coils</a></li>\r\n\t<li><a href="/">Tough Links</a></li>\r\n\t<li><a href="/">Key Identifiers</a></li>\r\n\t<li><a href="/">Key Rings</a></li>\r\n\t<li><a href="/">Lanyards</a></li>\r\n\t<li><a href="/">Key Retractors</a></li>\r\n\t<li><a href="/">Key Releases</a></li>\r\n\t<li><a href="/">Key Lights</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Keyblanks & Automotive',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 1',
        linkLabel: ' ',
        parentContent_linkUrl: '/shop/keyblanks-automotive',
        sortOrder: 30,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6f7a36001d',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'keyblanksautomotive',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column2',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808a74bb14de0174bc91b90d002d',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Keys</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Remotes</a></li>\r\n\t<li><a href="/">Auto Shells</a></li>\r\n\t<li><a href="/">Transponder Keys</a></li>\r\n\t<li><a href="/">Transponders</a></li>\r\n\t<li><a href="/">Transponder Heads</a></li>\r\n\t<li><a href="/">Transponder Blades</a></li>\r\n\t<li><a href="/">Vehicle</a></li>\r\n\t<li><a href="/">North American Cylinder</a></li>\r\n\t<li><a href="/">International Cylinder</a></li>\r\n\t<li><a href="/">Originals</a></li>\r\n\t<li><a href="/">Look-Alike</a></li>\r\n\t<li><a href="/">Safe Deposit</a></li>\r\n\t<li><a href="/">Flat Steel</a></li>\r\n\t<li><a href="/">Bit &amp; Barrel</a></li>\r\n\t<li><a href="/">Misc</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Keyblanks & Automotive',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 2',
        linkLabel: ' ',
        parentContent_linkUrl: '/shop/keyblanks-automotive',
        sortOrder: 34,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6f7a36001d',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'keyblanksautomotive',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column3',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808a74bb14de0174bc9292e7002f',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Automotive</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Keys</a></li>\r\n\t<li><a href="/">Remotes</a></li>\r\n\t<li><a href="/">Transponder Keys</a></li>\r\n\t<li><a href="/">Shells</a></li>\r\n\t<li><a href="/">Remote Head Keys</a></li>\r\n\t<li><a href="/">Auto Locks</a></li>\r\n\t<li><a href="/">Auto Tools</a></li>\r\n\t<li><a href="/">Programming Tools</a></li>\r\n\t<li><a href="/">Parts</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Keyblanks & Automotive',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 3',
        linkLabel: ' ',
        parentContent_linkUrl: '/shop/keyblanks-automotive',
        sortOrder: 36,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6e8fa2001b',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'cylindersrekeyingsuppliestools',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column1',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808a74bb14de0174bccba6680036',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Locksmith Tools</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Automotive Tools </a></li>\r\n\t<li><a href="/">Picks</a></li>\r\n\t<li><a href="/">Pin Kits</a></li>\r\n\t<li><a href="/">Hinge Repair </a></li>\r\n\t<li><a href="/">Keying Tools </a></li>\r\n\t<li><a href="/">Files</a></li>\r\n\t<li><a href="/">Drill Bits</a></li>\r\n\t<li><a href="/">Miscellaneous</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Cylinders, Rekeying Supplies & Tools',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 1',
        linkLabel: ' ',
        parentContent_linkUrl: ' ',
        sortOrder: 36,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6e8fa2001b',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'cylindersrekeyingsuppliestools',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-2',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808a74bb14de0174bccdaf200038',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">IC Cores, Housings </a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Rim Housings </a></li>\r\n\t<li><a href="/">Mortise Housings</a></li>\r\n\t<li><a href="/">IC Cores</a></li>\r\n\t<li><a href="/">Convertible Housings </a></li>\r\n\t<li><a href="/">Cams, Tailpieces &amp; Parts </a></li>\r\n\t<li><a href="/">Kits</a></li>\r\n\t<li><a href="/">Pins</a></li>\r\n\t<li><a href="/">Tools</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Cylinders, Rekeying Supplies & Tools',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 2',
        linkLabel: ' ',
        parentContent_linkUrl: ' ',
        sortOrder: 37,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6e8fa2001b',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'cylindersrekeyingsuppliestools',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column3',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808a74bb14de0174bccf1a89003a',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Cylinders</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Universal KIK/KIL/KID C-Clip </a></li>\r\n\t<li><a href="/">Universal KIK/KIL/KID Screwcap </a></li>\r\n\t<li><a href="/">Key-in-Knob</a></li>\r\n\t<li><a href="/">Key-in-Deadbolt</a></li>\r\n\t<li><a href="/">Mortise Cylinders</a></li>\r\n\t<li><a href="/">Specialty Cylinders</a></li>\r\n\t<li><a href="/">Dummy Cylinders </a></li>\r\n\t<li><a href="/">Thumbturn</a></li>\r\n\t<li><a href="/">Profile Cylinders</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Cylinders, Rekeying Supplies & Tools',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 3',
        linkLabel: ' ',
        parentContent_linkUrl: ' ',
        sortOrder: 38,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6e8fa2001b',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'cylindersrekeyingsuppliestools',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column4',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808a74bb14de0174bcd097c1003c',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Parts &amp; Components</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Cams</a></li>\r\n\t<li><a href="/">Tailpieces</a></li>\r\n\t<li><a href="/">Pins &amp; Pinning Parts </a></li>\r\n\t<li><a href="/">Collars</a></li>\r\n\t<li><a href="/">Plugs</a></li>\r\n\t<li><a href="/">Miscellaneous</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Cylinders, Rekeying Supplies & Tools',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 4',
        linkLabel: ' ',
        parentContent_linkUrl: ' ',
        sortOrder: 40,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6fe4a9001e',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'keymachinessafes',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-1',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808274d4e2120174d52f79430011',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Key Machines</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Manual</a></li>\r\n\t<li><a href="/">Semi-Automatic</a></li>\r\n\t<li><a href="/">Automatic</a></li>\r\n\t<li><a href="/">Tubular</a></li>\r\n\t<li><a href="/">Hi-Security Sidewinder </a></li>\r\n\t<li><a href="/">Code Origination</a></li>\r\n</ul>\r\n\r\n<p><a class="product-dropdown-header" href="/">Key Machine Replacement Parts </a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Cutters</a></li>\r\n\t<li><a href="/">Brushes</a></li>\r\n\t<li><a href="/">Parts</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Key Machines & Safes',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 1',
        linkLabel: ' ',
        parentContent_linkUrl: '/shop/key-machines-safes',
        sortOrder: 53,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc6fe4a9001e',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'keymachinessafes',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-2',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808274d4e2120174d531ae370012',
        cmsContentIDPath: ' ',
        customBody:
          '<p><a class="product-dropdown-header" href="/">Safes</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Burglary/Fire </a></li>\r\n\t<li><a href="/">Record</a></li>\r\n\t<li><a href="/">Depository</a></li>\r\n\t<li><a href="/">Under Counter Depository </a></li>\r\n\t<li><a href="/">Data-Media </a></li>\r\n\t<li><a href="/">Single Door Depository </a></li>\r\n\t<li><a href="/">Wide Body/Oversized </a></li>\r\n\t<li><a href="/">Gun</a></li>\r\n\t<li><a href="/">In-Room </a></li>\r\n\t<li><a href="/">Jewelry</a></li>\r\n\t<li><a href="/">Microwave</a></li>\r\n\t<li><a href="/">Wall Safe (Concealed) </a></li>\r\n\t<li><a href="/">Wall Safe (Insulated) </a></li>\r\n\t<li><a href="/">Record</a></li>\r\n\t<li><a href="/">Pistol</a></li>\r\n\t<li><a href="/">Parts</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Key Machines & Safes',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 2',
        linkLabel: ' ',
        parentContent_linkUrl: '/shop/key-machines-safes',
        sortOrder: 55,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc7039ac001f',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'doorhardware',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-1',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808274d4e2120174d53513d80013',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Door Closers &amp; Operators </a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Automatic Operators</a></li>\r\n\t<li><a href="/">Heavy Duty </a></li>\r\n\t<li><a href="/">Medium Duty</a></li>\r\n\t<li><a href="/">Light Duty</a></li>\r\n\t<li><a href="/">Door Closer Parts </a></li>\r\n</ul>\r\n\r\n<p><a class="product-dropdown-header" href="/">Electric Strikes</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Surface Mount Style </a></li>\r\n\t<li><a href="/">In-Frame Style </a></li>\r\n\t<li><a href="/">For Rim Exits </a></li>\r\n\t<li><a href="/">For Cylindrical Locksets </a></li>\r\n\t<li><a href="/">For Mortise Locks </a></li>\r\n\t<li><a href="/">Fire Rated</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Door Hardware',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 1',
        linkLabel: ' ',
        parentContent_linkUrl: 'shop/door-hardware',
        sortOrder: 55,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc7039ac001f',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'doorhardware',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-2',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808274d4e2120174d537b70d0014',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Mortise Locks </a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Complete Mortise Locks </a></li>\r\n\t<li><a href="/">Mortise Bodies </a></li>\r\n\t<li><a href="/">Mortise Trims </a></li>\r\n</ul>\r\n\r\n<p><a class="product-dropdown-header" href="/">Bored Locks &amp; Deadbolts</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Knobs</a></li>\r\n\t<li><a href="/">Levers</a></li>\r\n\t<li><a href="/">Deadbolts</a></li>\r\n\t<li><a href="/">Grade 1 </a></li>\r\n\t<li><a href="/">Grade 2 </a></li>\r\n\t<li><a href="/">Residential</a></li>\r\n\t<li><a href="/">Electronic</a></li>\r\n\t<li><a href="/">Mechanical</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Door Hardware',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 2',
        linkLabel: ' ',
        parentContent_linkUrl: 'shop/door-hardware',
        sortOrder: 56,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc7039ac001f',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'doorhardware',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-3',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808274d4e2120174d53a123d0015',
        cmsContentIDPath: ' ',
        customBody:
          '<p><a class="product-dropdown-header" href="/">Storefront Hardware</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Deadlatches</a></li>\r\n\t<li><a href="/">Deadbolts</a></li>\r\n\t<li><a href="/">Hookbolts</a></li>\r\n\t<li><a href="/">Paddles/Levers </a></li>\r\n\t<li><a href="/">Parts &amp; Accessories </a></li>\r\n</ul>\r\n\r\n<p><a class="product-dropdown-header" href="/">Access Control</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Keypads</a></li>\r\n\t<li><a href="/">Power Supplies </a></li>\r\n\t<li><a href="/">Readers</a></li>\r\n\t<li><a href="/">Cards &amp; Fobs </a></li>\r\n\t<li><a href="/">Gateways &amp; Expanders </a></li>\r\n\t<li><a href="/">Request to Exit </a></li>\r\n\t<li><a href="/">Mag Locks </a></li>\r\n\t<li><a href="/">Parts &amp; Accessories</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Door Hardware',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 3',
        linkLabel: ' ',
        parentContent_linkUrl: 'shop/door-hardware',
        sortOrder: 57,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc7039ac001f',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'doorhardware',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-4',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808274d4e2120174d53e0ae30016',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Pushbutton Locks</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Mechanical</a></li>\r\n\t<li><a href="/">Electronic Standalone </a></li>\r\n\t<li><a href="/">Electronic Networked </a></li>\r\n</ul>\r\n\r\n<p><a class="product-dropdown-header" href="/">Exit Devices &amp; Exit Alarms </a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Rim Exit Devices </a></li>\r\n\t<li><a href="/">Mortise Exit Devices </a></li>\r\n\t<li><a href="/">Vertical Rod </a></li>\r\n\t<li><a href="/">Trim</a></li>\r\n\t<li><a href="/">Exit Alarms </a></li>\r\n\t<li><a href="/">Latch Retraction Kits </a></li>\r\n\t<li><a href="/">Alarm Kits </a></li>\r\n\t<li><a href="/">Parts</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Door Hardware',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 4',
        linkLabel: ' ',
        parentContent_linkUrl: 'shop/door-hardware',
        sortOrder: 59,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc70a08b0020',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'buildershardwareutilitylocks',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-1',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808274d4e2120174d5425f320017',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Cam Locks &amp; Auxiliary Locks</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Drawer Locks </a></li>\r\n\t<li><a href="/">Cam Locks </a></li>\r\n\t<li><a href="/">Door Locks </a></li>\r\n\t<li><a href="/">Cabinet Locks </a></li>\r\n\t<li><a href="/">Auxiliary Locks </a></li>\r\n\t<li><a href="/">Mailbox Locks </a></li>\r\n\t<li><a href="/">Regulator</a></li>\r\n\t<li><a href="/">Replacement Knobs </a></li>\r\n\t<li><a href="/">Window Locks </a></li>\r\n\t<li><a href="/">Showcase Locks </a></li>\r\n\t<li><a href="/">Desk Locks</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Builders Hardware & Utility Locks',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 1',
        linkLabel: ' ',
        parentContent_linkUrl: '/shop/builders-hardware-utility-locks',
        sortOrder: 59,
      },
      {
        contentBody: ' ',
        parentContent_contentID: '2c91808a74bb14de0174bc70a08b0020',
        contentIDPath: ' ',
        disableProductAssignmentFlag: ' ',
        parentContent_urlTitle: 'buildershardwareutilitylocks',
        productSortDefaultDirection: ' ',
        titlePath: ' ',
        allowPurchaseFlag: ' ',
        templateFlag: ' ',
        productListingPageFlag: ' ',
        productSortProperty: ' ',
        customSummary: ' ',
        excludeFromSearch: ' ',
        activeFlag: ' ',
        urlTitle: 'column-2',
        site_siteCode: 'stoneAndBerg',
        associatedImage: ' ',
        contentID: '2c91808274d4e2120174d5445a810018',
        cmsContentIDPath: ' ',
        customBody: '<p><a class="product-dropdown-header" href="/">Builder&#39;s Hardware</a></p>\r\n\r\n<ul>\r\n\t<li><a href="/">Accessory Hardware </a></li>\r\n\t<li><a href="/">Bolts &amp; Latches </a></li>\r\n\t<li><a href="/">Kick Plates </a></li>\r\n\t<li><a href="/">Push/Pull Plates </a></li>\r\n\t<li><a href="/">Door Stops, Holders &amp; Bumpers </a></li>\r\n\t<li><a href="/">Door Signs </a></li>\r\n\t<li><a href="/">Hinges</a></li>\r\n\t<li><a href="/">Continuous Hinges </a></li>\r\n\t<li><a href="/">Latch Protectors </a></li>\r\n\t<li><a href="/">Strike Plates </a></li>\r\n\t<li><a href="/">Wrap-Around Plates</a></li>\r\n</ul>\r\n',
        parentContent_title: 'Builders Hardware & Utility Locks',
        urlTitlePath: ' ',
        linkUrl: ' ',
        displayInNavigation: ' ',
        title: 'Column 2',
        linkLabel: ' ',
        parentContent_linkUrl: '/shop/builders-hardware-utility-locks',
        sortOrder: 61,
      },
    ],
    'footer/site-links': '<h3>Site Links</h3><ul><li><a href="/">Home</a></li><li><a href="/products">Products</a></li><li><a href="/about">About</a></li><li><a href="/contact">Contact</a></li><li><a href="/my-account">My Account</a></li></ul>',
    'footer/get-in-touch': '<h3>Get in Touch</h3><ul><li>(508) 753-3551</li><li>Toll Free: (800)535-5625</li><li><a href="http://emailto:orders@stoneandberg.com">orders@stoneandberg.com</a></li><li>Monday - Friday: 8AM - 5PM</li></ul><p>&nbsp;</p><ul><li>239 Mill Street</li><li>Worcester, MA 01602</li></ul>',
  },

  footer: {
    formLink: 'https://stoneandberg.us3.list-manage.com/subscribe/post?u=8eee6b8b93baf1968074021ef&id=ddc565ac59',
  },

  categoryListing: {
    template: 'category-listing',
    title: 'Shop Door Hardware',
    crumbs: [
      { slug: '/', title: 'Home' },
      { slug: '/products', title: 'Products' },
      { slug: '/products/door-hardware', title: 'Door Hardware' },
    ],
    categories: [
      {
        heading: 'Door Closers & Operators',
        items: [
          { title: 'Automatic Operators', link: '/#' },
          { title: 'Heavy Duty', link: '/#' },
          { title: 'Medium Duty', link: '/#' },
          { title: 'Light Duty', link: '/#' },
          { title: 'Heavy Duty', link: '/#' },
          { title: 'Door Closer Parts', link: '/#' },
        ],
      },
      {
        heading: 'Storefront Hardware',
        items: [
          { title: 'Deadlatches', link: '/#' },
          { title: 'Deadbolts', link: '/#' },
          { title: 'Hookbolts', link: '/#' },
          { title: 'Paddles/Levers', link: '/#' },
          { title: 'Parts & Accessories', link: '/#' },
        ],
      },
      {
        heading: 'Electric Strikes',
        items: [
          { title: 'Surface Mount Style', link: '/#' },
          { title: 'In-Frame Style', link: '/#' },
          { title: 'For Rim Exits', link: '/#' },
          { title: 'For Cylindrical Locksets', link: '/#' },
          { title: 'For Mortise Locks', link: '/#' },
          { title: 'Fire Rated', link: '/#' },
        ],
      },
    ],
    customBody: '<p><strong>Stone &amp; Berg</strong><br /> 239 Mill Street<br /> Worcester MA 01602</p> <p>Phone: (508) 753-3551<br /> Toll Free: (800) 225-7405<br /> Fax: (800) 535-5625</p> <p><strong>Email</strong><br /> orders@stoneandberg.com</p> <p><strong>Hours</strong><br /> Monday - Friday<br /> 8AM - 5PM</p>',
    customSummary: '<h2>We are here to help. Contact us with any questions.</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo.</p>',
  },
  accountOverview: {
    crumbs: [
      { slug: '/', title: 'Home' },
      { slug: '/my-account', title: 'Account' },
    ],
    template: 'account-dashboard',
    title: 'My Dashboard',
    contentTitle: 'Welcome to Stone and Berg',
    customBody: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar sic tempor. Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus pronin sapien nunc accuan eget.</p> <p><a href="/shop">Start Shopping</a></p>',
    customSummary: '',
  },
  accountProfile: {
    crumbs: [
      { slug: '/', title: 'Home' },
      { slug: '/my-account', title: 'Account' },
      { slug: '/my-account/profile', title: 'Profile' },
    ],
    template: 'account-profile',
    title: 'My Profile',
    contentTitle: 'Update your profile details below:',
    customBody: '',
    customSummary: '',
  },
  accountOrderHistory: {
    crumbs: [
      { slug: '/', title: 'Home' },
      { slug: '/my-account', title: 'Account' },
      { slug: '/my-account/order-history', title: 'Order History' },
    ],
    template: 'order-history',
    title: 'My Orders',
    contentTitle: '',
    customBody: '',
    customSummary: '',
    orders: [
      {
        number: '34VB5540K83',
        location: 'PO: 51705',
        datePurchased: 'May 21, 2019',
        status: 'New',
        statusType: 'info',
        total: '$358.75',
        trackingNumbers: ['573289573802', '643068306672'],
      },

      {
        number: '78A643CD409',
        location: '',
        datePurchased: 'December 09, 2018',
        status: 'Canceled',
        statusType: 'danger',
        total: '$760.50',
        trackingNumbers: ['573289573802', '643068306672'],
      },

      {
        number: '112P45A90V2',
        location: '',
        datePurchased: 'October 15, 2018',
        status: 'Partially Shipped',
        statusType: 'warning',
        total: '$1,264.00',
        trackingNumbers: ['573289573802', '643068306672'],
      },

      {
        number: '28BA67U0981',
        location: '',
        datePurchased: 'July 19, 2018',
        status: 'Complete',
        statusType: 'success',
        total: '$198.35',
        trackingNumbers: ['573289573802', '643068306672'],
      },

      {
        number: '502TR872W2',
        location: '',
        datePurchased: 'April 04, 2018',
        status: 'Complete',
        statusType: 'success',
        total: '$2,133.90',
        trackingNumbers: ['573289573802', '643068306672'],
      },

      {
        number: '47H76G09F33',
        location: '',
        datePurchased: 'March 30, 2018',
        status: 'Complete',
        statusType: 'success',
        total: '$86.40',
        trackingNumbers: ['573289573802', '643068306672'],
      },
    ],
  },
  accountFavorites: {
    crumbs: [
      { slug: '/', title: 'Home' },
      { slug: '/my-account', title: 'Account' },
      { slug: '/my-account/favorites', title: 'Favorites' },
    ],
    template: 'order-history',
    title: 'My Favorites',
    contentTitle: '',
    customBody: '',
    customSummary: '',
    items: [
      {
        brand: 'Brand A',
        productTile: 'Title 1',
        price: '$209.24',
        displayPrice: '$156.99',
        linkUrl: '/hop-single-v1.html',
      },
      {
        brand: 'Brand A',
        productTile: 'Title 1',
        price: '$209.24',
        displayPrice: '$156.99',
        linkUrl: '/shop-single-v1.html',
      },
      {
        brand: 'Brand A',
        productTile: 'Title 1',
        price: '$209.24',
        displayPrice: '$156.99',
        linkUrl: '/shop-single-v1.html',
      },
      {
        brand: 'Brand A',
        productTile: 'Title 1',
        price: '$209.24',
        displayPrice: '$156.99',
        linkUrl: '/shop-single-v1.html',
      },
    ],
  },
  accountAddresses: {
    crumbs: [
      { slug: '/', title: 'Home' },
      { slug: '/my-account', title: 'Account' },
      { slug: '/my-account/addresses', title: 'Addresses' },
    ],
    template: 'account-address',
    title: 'My Addresses',
    contentTitle: 'List of your registered addresses:',
    customBody: '',
    customSummary: '',
    addresses: [
      {
        location: '396 Lillian Blvd, Holbrook, NY 11741, USA',
        isPrimary: true,
      },
      {
        location: '769, Industrial, West Chicago, IL 60185, USA',
        isPrimary: false,
      },
      {
        location: '514 S. Magnolia St. Orlando, FL 32806, USA',
        isPrimary: false,
      },
    ],
  },
  accountPaymentMethods: {
    crumbs: [
      { slug: '/', title: 'Home' },
      { slug: '/my-account', title: 'Account' },
      { slug: '/my-account/cards', title: 'Payment Methods' },
    ],
    template: 'cards',
    title: 'Payment Methods',
    contentTitle: 'Primary payment method is used by default',
    customBody: '',
    customSummary: '',
    paymentMethods: [
      {
        type: 'Visa',
        ending: 'ending in 4999',
        isPrimary: true,
        name: 'Susan Gardner',
        expirationDate: '08 / 2019',
      },
      {
        type: 'MasterCard',
        ending: 'ending in 0015',
        isPrimary: false,
        name: 'Susan Gardner',
        expirationDate: '11 / 2021',
      },
      {
        type: 'Visa',
        ending: 'ending in 6073',
        isPrimary: false,
        name: 'Susan Gardner',
        expirationDate: '09 / 2021',
      },
      {
        type: 'Visa',
        ending: 'ending in 9791',
        isPrimary: false,
        name: 'Susan Gardner',
        expirationDate: '05 / 2021',
      },
    ],
  },
  theme: {
    host: 'https://stoneandberg.ten24dev.com',
    basePath: '/custom/client/assets/images/',
  },
  productListing: {
    crumbs: [
      { slug: '/', title: 'Home' },
      { slug: '/products', title: 'Shop' },
      { slug: '/products', title: 'Door Closers & Operators' },
    ],
    template: 'product-listing',
    title: 'Door Closers & Operators',
    contentTitle: '',
    customBody: '',
    customSummary: '',
  },
}
